# Generated by Django 6.0.1 on 2026-01-30 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_parser', '0004_telegrampost_telegramcomment_delete_telegramuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telegrampost',
            unique_together={('channel', 'post_id')},
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='parsed_by',
            field=models.ManyToManyField(related_name='parsed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='telegrampost',
            name='user',
        ),
    ]
